### ISSUE TITLE
Suggestion Graceful error catching

### ISSUE THREAD

**Issue by CmdrAdama** [canonn-science/EDMC-Canonn#16]
Is it possible to add a plugin level catch of unexpected errors so that, at worst, the plugin stops working but EDMC doesn’t crash

**Comment by NoFoolLikeOne** [comment]
I don't think it is possible in this instance because the error occurs in tkinter which is not thread safe. So the error could occur randomly in any part of the program and crash EDMC

I'm going through each of the modules to make sure that there is no TKInter code being called in the threads, 

As a last resort I'll change the inheritance model so that it doesn't inherit from Frame

**Comment by NoFoolLikeOne** [comment]
Release 1.6.0 has some logging in debug when the threads are entered, so we should be able to see what module caused the problem.

I'm going to close this as I think this is the best that we can do.
