### ISSUE TITLE
[BUG] Patrols not hidden

### ISSUE THREAD

**Issue by fnordson** [canonn-science/EDMC-Canonn#72]
**What is your commander name**
Althalen Sorhn

**What version are you running**
5.10.0

**Describe the bug**
Plugin not hiding Patrols even though hiding is checked since this version

**To Reproduce**
Check "Hide Canonn Patrols" box, start EDMC

**Expected behavior**
No patrols displayed. 

**Screenshots**
![canonn](https://user-images.githubusercontent.com/5624605/76793289-16fb2f00-67c5-11ea-84f5-ac58d9e9edd7.jpg)

**Comment by VAKazakov** [comment]
Patrol on interface contains several data sources, each disabling by separate option in Settings. Hide Canonn Patrol option disabling only Exploring tasks, downloaded from Canonn API. If you want fully disable Patrol on Interface, you need to activate all options since Hide Patrol till Hide your ships. I hope that helps

**Comment by fnordson** [comment]
Ah got it. Had to restart EDSM so it works. 
I did that before but nothing happened so I assumed that's not it...sorry.
